# Site settings
# in the templates available like {{ site.myvariable }}.
title: Clean portfolio theme for Jekyll powered by Bootstrap 4.
email: bettina.offenegger@gmail.com 
brand: Bettina Maria
headline: Full Stack Web Developer Student, Nomadic Traveller, Language Enthusiast
description: > # this means to ignore newlines until "baseurl:"
  New Site
baseurl: "bettinamaria.io/instagram" # the subpath of your site, e.g. /blog
url: "http://bettinamaria.github.io" # the base hostname & protocol for your site
copyright: 2017 Bettina Offenegger

# Build settings
markdown: kramdown

# Account ids
snapwidget: 247552

# Contacts
email: bettina.offenegger@gmail.com
phone: 

# Tracking
googleAnalitycsID: UA-83933844-1

